M48
; DRILL file {KiCad 7.0.5} date Mon Jul 31 22:06:35 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-31T22:06:35-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X7.7376Y-3.8339
X7.8876Y-3.8339
T2
X6.3051Y-3.2311
X6.3051Y-3.6811
T0
M30
