M48
; DRILL file {KiCad 7.0.5} date Wed Aug  2 13:43:57 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-02T13:43:57-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X7.7376Y-3.8339
X7.8876Y-3.8339
T2
X6.2917Y-3.3904
X6.2917Y-3.8404
T0
M30
